# Generated by Django 2.1.4 on 2019-12-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('creation_type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('creation_image', models.ImageField(height_field=1080, upload_to='uploads', verbose_name='creation image', width_field=1920)),
            ],
            options={
                'verbose_name': 'creation',
                'verbose_name_plural': 'creations',
            },
        ),
    ]
