# Generated by Django 2.1.4 on 2019-12-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='creation_image',
            field=models.ImageField(upload_to='uploads', verbose_name='creation image'),
        ),
    ]
