# Generated by Django 2.1.4 on 2019-12-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0002_auto_20191231_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=100)),
                ('punchline', models.CharField(max_length=150)),
                ('site_email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phoneNo', models.TextField(max_length=15)),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('youtube', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_name', models.CharField(max_length=100)),
                ('slider_url', models.URLField()),
                ('slider_image', models.ImageField(upload_to='sliders', verbose_name='slider image')),
            ],
        ),
    ]
